version: 0.0
os: linux
files:
	- source:/
	  destination: /var/www/html/iftibd
permissions:
	- obejcts: /var/www/html/iftibd
		pattern: "**"
		owner: www-data
		group: www-data
		mode: 755
		type:
		-file
